title: linus luu
description: a pretty cool website
author: linus luu
theme: minima

# Navigation links
navbar:
  - title: Home
    url: /
  - title: About
    url: /about

# Social media links
social_links:
  - title: blog
    url: https://linusluu.wordpress.com
  - title: twitter
    url: https://twitter.com/linusluu_
